/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaAlgorithms;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import javaAlgorithms.insertionSort;

class AppTest {
	@Test 
	void testInsertionSort() {
		int[] array1 = {2, 1};
		int[] array1Sorted = {1, 2};
		insertionSort.insertionSortInt(array1);
		assertArrayEquals(array1Sorted, array1);

		int[] array2 = {3, 2, 0, 1};
		int[] array2Sorted = {0, 1, 2, 3};
		insertionSort.insertionSortInt(array2);
		assertArrayEquals(array2Sorted, array2);

		int[] array3 = {8, 6, 7, 5, 3, 0, 9};
		int[] array3Sorted = {0, 3, 5, 6, 7, 8, 9};
		insertionSort.insertionSortInt(array3);
		assertArrayEquals(array3Sorted, array3);

		int[] array4 = {1004, 33919, 4913, 2, 3123, 444};
		int[] array4Sorted = {2, 444, 1004, 3123, 4913, 33919};
		insertionSort.insertionSortInt(array4);
		assertArrayEquals(array4Sorted, array4);

		int[] array5 = {};
		int[] array5Sorted = {};
		insertionSort.insertionSortInt(array5);
		assertArrayEquals(array5Sorted, array5);
	}
}
